meta_data = {
    'Mahapallegama': {'lon_lat': [80.2586, 7.16984],
                      'run_name': 'A&T Labs',
                      'variable': 'Precipitation',
                      'unit': 'mm',
                      'event_type': 'Observed',
                      'source': 'WeatherStation'},
    'Hingurana': {'lon_lat': [80.40782, 6.90449],
                  'run_name': 'CUrW IoT',
                  'variable': 'Precipitation',
                  'unit': 'mm',
                  'event_type': 'Observed',
                  'source': 'WeatherStation'},
    'Dickoya': {'lon_lat': [80.60312, 6.8722],
                'run_name': 'A&T Labs',
                'variable': 'Precipitation',
                'unit': 'mm',
                'event_type': 'Observed',
                'source': 'WeatherStation'},
    'Waga': {'lon_lat': [80.60312, 6.90678],
             'run_name': 'A&T Labs',
             'variable': 'Precipitation',
             'unit': 'mm',
             'event_type': 'Observed',
             'source': 'WeatherStation'},
    'Hanwella': {'lon_lat': [80.081667, 6.909722],
                 'run_name': 'Irrigation Department',
                 'variable': 'Precipitation',
                 'unit': 'mm',
                 'event_type': 'Observed',
                 'source': 'WeatherStation'},
    'Norton Bridge': {'lon_lat': [80.516, 6.9],
                      'run_name': 'Irrigation Department',
                      'variable': 'Precipitation',
                      'unit': 'mm',
                      'event_type': 'Observed',
                      'source': 'WeatherStation'},
    'Kitulgala': {'lon_lat': [80.41777, 6.98916],
                  'run_name': 'Irrigation Department',
                  'variable': 'Precipitation',
                  'unit': 'mm',
                  'event_type': 'Observed',
                  'source': 'WeatherStation'},
    'Holombuwa': {'lon_lat': [80.26480, 7.18516],
                  'run_name': 'Irrigation Department',
                  'variable': 'Precipitation',
                  'unit': 'mm',
                  'event_type': 'Observed',
                  'source': 'WeatherStation'},
    'Daraniyagala': {'lon_lat': [80.33805, 6.92444],
                     'run_name': 'Irrigation Department',
                     'variable': 'Precipitation',
                     'unit': 'mm',
                     'event_type': 'Observed',
                     'source': 'WeatherStation'},
    'Glencourse': {'lon_lat': [80.20305, 6.97805],
                   'run_name': 'Irrigation Department',
                   'variable': 'Precipitation',
                   'unit': 'mm',
                   'event_type': 'Observed',
                   'source': 'WeatherStation'},
    'Norwood': {'lon_lat': [80.61466, 6.83563],
                   'run_name': 'Irrigation Department',
                   'variable': 'Precipitation',
                   'unit': 'mm',
                   'event_type': 'Observed',
                   'source': 'WeatherStation'}
}